namespace DraCode.KoboldLair.Models.Projects
{
    /// <summary>
    /// File paths associated with a project
    /// </summary>
    public class ProjectPaths
    {
        /// <summary>
        /// Path to the specification file
        /// </summary>
        public string Specification { get; set; } = "";

        /// <summary>
        /// Directory where output files will be stored
        /// </summary>
        public string Output { get; set; } = "";

        /// <summary>
        /// Path to the Wyrm analysis output (if generated)
        /// </summary>
        public string? Analysis { get; set; }

        /// <summary>
        /// Task files generated by Wyvern (area -> file path)
        /// </summary>
        public Dictionary<string, string> TaskFiles { get; set; } = new();
    }
}
