namespace DraCode.KoboldLair.Server.Models
{
    /// <summary>
    /// Represents a project in the KoboldLair system.
    /// Created when Dragon generates a specification, assigned a Wyvern for analysis.
    /// </summary>
    public class Project
    {
        /// <summary>
        /// Unique identifier for the project
        /// </summary>
        public string Id { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// Name of the project
        /// </summary>
        public string Name { get; set; } = "";

        /// <summary>
        /// Path to the specification file
        /// </summary>
        public string SpecificationPath { get; set; } = "";

        /// <summary>
        /// ID of the specification associated with this project
        /// </summary>
        public string? SpecificationId { get; set; }

        /// <summary>
        /// Specification object (when loaded)
        /// </summary>
        public Specification? Specification { get; set; }

        /// <summary>
        /// Directory where output files will be stored
        /// </summary>
        public string OutputPath { get; set; } = "";

        /// <summary>
        /// ID of the Wyvern assigned to this project
        /// </summary>
        public string? WyvernId { get; set; }

        /// <summary>
        /// Current status of the project
        /// </summary>
        public ProjectStatus Status { get; set; } = ProjectStatus.New;

        /// <summary>
        /// When the project was created
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// When the project was last updated
        /// </summary>
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// When Wyvern analysis was completed (if applicable)
        /// </summary>
        public DateTime? AnalyzedAt { get; set; }

        /// <summary>
        /// When the specification was last processed by Wyvern.
        /// Used to detect if specification file has been modified since last processing.
        /// </summary>
        public DateTime? LastProcessedAt { get; set; }

        /// <summary>
        /// Hash of specification content at last processing.
        /// Used to detect content changes even if file timestamp is unreliable.
        /// </summary>
        public string? LastProcessedContentHash { get; set; }

        /// <summary>
        /// Path to the Wyrm analysis output (if generated)
        /// </summary>
        public string? AnalysisOutputPath { get; set; }

        /// <summary>
        /// Task files generated by Wyvern
        /// </summary>
        public Dictionary<string, string> TaskFiles { get; set; } = new();

        /// <summary>
        /// Areas that still need tasks assigned (for incremental processing)
        /// </summary>
        public List<string> PendingAreas { get; set; } = new();

        /// <summary>
        /// Error message if processing failed
        /// </summary>
        public string? ErrorMessage { get; set; }

        /// <summary>
        /// Additional metadata
        /// </summary>
        public Dictionary<string, string> Metadata { get; set; } = new();

        /// <summary>
        /// Maximum number of parallel Kobolds allowed for this project
        /// </summary>
        public int MaxParallelKobolds { get; set; } = 5;
    }
}
