namespace DraCode.KoboldLair.Server.Models
{
    /// <summary>
    /// Represents a project in the KoboldTown system.
    /// Created when Dragon generates a specification, assigned a Wyrm for analysis.
    /// </summary>
    public class Project
    {
        /// <summary>
        /// Unique identifier for the project
        /// </summary>
        public string Id { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// Name of the project
        /// </summary>
        public string Name { get; set; } = "";

        /// <summary>
        /// Path to the specification file
        /// </summary>
        public string SpecificationPath { get; set; } = "";

        /// <summary>
        /// Directory where output files will be stored
        /// </summary>
        public string OutputPath { get; set; } = "";

        /// <summary>
        /// ID of the Wyrm assigned to this project
        /// </summary>
        public string? WyrmId { get; set; }

        /// <summary>
        /// Current status of the project
        /// </summary>
        public ProjectStatus Status { get; set; } = ProjectStatus.New;

        /// <summary>
        /// When the project was created
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// When the project was last updated
        /// </summary>
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// When Wyrm analysis was completed (if applicable)
        /// </summary>
        public DateTime? AnalyzedAt { get; set; }

        /// <summary>
        /// Path to the Wyrm analysis output (if generated)
        /// </summary>
        public string? AnalysisOutputPath { get; set; }

        /// <summary>
        /// Task files generated by Wyrm
        /// </summary>
        public Dictionary<string, string> TaskFiles { get; set; } = new();

        /// <summary>
        /// Error message if processing failed
        /// </summary>
        public string? ErrorMessage { get; set; }

        /// <summary>
        /// Additional metadata
        /// </summary>
        public Dictionary<string, string> Metadata { get; set; } = new();

        /// <summary>
        /// Provider settings for this project's agents
        /// </summary>
        public ProjectProviderSettings ProviderSettings { get; set; } = new();
    }

    /// <summary>
    /// Provider configuration for a specific project
    /// </summary>
    public class ProjectProviderSettings
    {
        /// <summary>
        /// Provider used for the Wyrm agent analyzing this project
        /// </summary>
        public string? WyrmProvider { get; set; }

        /// <summary>
        /// Model override for Wyrm (if any)
        /// </summary>
        public string? WyrmModel { get; set; }

        /// <summary>
        /// Whether Wyrm analysis is enabled for this project
        /// </summary>
        public bool WyrmEnabled { get; set; } = false;

        /// <summary>
        /// Provider used for Drake supervisors in this project
        /// </summary>
        public string? DrakeProvider { get; set; }

        /// <summary>
        /// Model override for Drakes (if any)
        /// </summary>
        public string? DrakeModel { get; set; }

        /// <summary>
        /// Whether Drake supervisors are enabled for this project
        /// </summary>
        public bool DrakeEnabled { get; set; } = false;

        /// <summary>
        /// Provider used for Kobold workers in this project
        /// </summary>
        public string? KoboldProvider { get; set; }

        /// <summary>
        /// Model override for Kobolds (if any)
        /// </summary>
        public string? KoboldModel { get; set; }

        /// <summary>
        /// Whether Kobold workers are enabled for this project
        /// </summary>
        public bool KoboldEnabled { get; set; } = false;

        /// <summary>
        /// Timestamp when provider settings were last updated
        /// </summary>
        public DateTime? LastUpdated { get; set; }
    }
}
