using System.Text;
using DraCode.Agent.Tools;
using DraCode.KoboldLair.Services;

namespace DraCode.KoboldLair.Agents.Tools
{
    /// <summary>
    /// Tool for browsing workspace/output files generated by Kobolds for a project.
    /// </summary>
    public class ViewWorkspaceTool : Tool
    {
        private readonly ProjectService _projectService;

        public ViewWorkspaceTool(ProjectService projectService)
        {
            _projectService = projectService;
        }

        public override string Name => "view_workspace";

        public override string Description =>
            "Browse the workspace (output) files generated by Kobolds for a project. " +
            "Actions: 'tree' shows the file tree structure, 'stats' shows file counts and sizes by type, " +
            "'recent' shows recently modified files.";

        public override object? InputSchema => new
        {
            type = "object",
            properties = new
            {
                action = new
                {
                    type = "string",
                    description = "Action: 'tree' (file tree), 'stats' (file statistics), 'recent' (recently modified files)",
                    @enum = new[] { "tree", "stats", "recent" }
                },
                project = new
                {
                    type = "string",
                    description = "Project ID or name"
                },
                path = new
                {
                    type = "string",
                    description = "Optional: subdirectory within workspace to browse (for 'tree' action)"
                },
                depth = new
                {
                    type = "integer",
                    description = "Optional: maximum depth for tree display (default: 3)"
                }
            },
            required = new[] { "action", "project" }
        };

        public override string Execute(string workingDirectory, Dictionary<string, object> input)
        {
            var action = input.TryGetValue("action", out var actionVal)
                ? actionVal?.ToString()?.ToLowerInvariant()
                : "tree";

            if (!input.TryGetValue("project", out var projectVal) || string.IsNullOrEmpty(projectVal?.ToString()))
            {
                return "Error: 'project' parameter is required.";
            }

            var projectIdOrName = projectVal.ToString()!;
            var project = FindProject(projectIdOrName);
            if (project == null)
                return $"Project '{projectIdOrName}' not found.";

            var workspacePath = project.Paths?.Output;
            if (string.IsNullOrEmpty(workspacePath))
                return $"No workspace path configured for project '{project.Name}'.";

            var resolvedPath = Path.IsPathRooted(workspacePath)
                ? workspacePath
                : Path.Combine(_projectService.ProjectsPath, workspacePath);

            if (!Directory.Exists(resolvedPath))
                return $"Workspace directory does not exist yet: `{workspacePath}`\nKobolds will create it when they start working on tasks.";

            return action switch
            {
                "tree" => ExecuteTree(resolvedPath, input),
                "stats" => ExecuteStats(resolvedPath),
                "recent" => ExecuteRecent(resolvedPath),
                _ => $"Unknown action: {action}. Use 'tree', 'stats', or 'recent'."
            };
        }

        private string ExecuteTree(string basePath, Dictionary<string, object> input)
        {
            try
            {
                // Optional subdirectory
                var subPath = input.TryGetValue("path", out var pathVal) ? pathVal?.ToString() : null;
                var targetPath = string.IsNullOrEmpty(subPath) ? basePath : Path.Combine(basePath, subPath);

                if (!Directory.Exists(targetPath))
                    return $"Directory not found: `{subPath}`";

                var maxDepth = 3;
                if (input.TryGetValue("depth", out var depthVal))
                {
                    if (int.TryParse(depthVal?.ToString(), out var d))
                        maxDepth = Math.Clamp(d, 1, 6);
                }

                var sb = new StringBuilder();
                sb.AppendLine($"**Workspace:** `{Path.GetFileName(basePath)}/`");
                if (!string.IsNullOrEmpty(subPath))
                    sb.AppendLine($"**Path:** `{subPath}/`");
                sb.AppendLine();

                var fileCount = 0;
                BuildTree(sb, targetPath, basePath, 0, maxDepth, ref fileCount);

                sb.AppendLine();
                sb.AppendLine($"*{fileCount} file(s) shown (max depth: {maxDepth})*");

                return sb.ToString();
            }
            catch (Exception ex)
            {
                return $"Error building file tree: {ex.Message}";
            }
        }

        private void BuildTree(StringBuilder sb, string dirPath, string basePath, int depth, int maxDepth, ref int fileCount, string indent = "")
        {
            if (depth > maxDepth) return;

            try
            {
                var dirs = Directory.GetDirectories(dirPath).OrderBy(d => d).ToArray();
                var files = Directory.GetFiles(dirPath).OrderBy(f => f).ToArray();

                foreach (var dir in dirs)
                {
                    var dirName = Path.GetFileName(dir);
                    // Skip common non-essential directories
                    if (dirName is ".git" or "node_modules" or "bin" or "obj" or ".vs")
                        continue;

                    var subFiles = Directory.GetFiles(dir, "*", SearchOption.AllDirectories).Length;
                    sb.AppendLine($"{indent}📁 **{dirName}/** ({subFiles} files)");

                    if (depth < maxDepth)
                        BuildTree(sb, dir, basePath, depth + 1, maxDepth, ref fileCount, indent + "  ");
                }

                foreach (var file in files)
                {
                    var fileName = Path.GetFileName(file);
                    var size = new FileInfo(file).Length;
                    var sizeStr = FormatSize(size);
                    var icon = GetFileIcon(fileName);
                    sb.AppendLine($"{indent}{icon} {fileName} ({sizeStr})");
                    fileCount++;

                    if (fileCount >= 100)
                    {
                        sb.AppendLine($"{indent}*... truncated at 100 files*");
                        return;
                    }
                }
            }
            catch (UnauthorizedAccessException)
            {
                sb.AppendLine($"{indent}⚠️ (access denied)");
            }
        }

        private string ExecuteStats(string basePath)
        {
            try
            {
                var allFiles = Directory.GetFiles(basePath, "*", SearchOption.AllDirectories);

                if (allFiles.Length == 0)
                    return "Workspace is empty. No files generated yet.";

                var sb = new StringBuilder();
                sb.AppendLine("## Workspace Statistics\n");

                // Group by extension
                var byExtension = allFiles
                    .GroupBy(f => Path.GetExtension(f).ToLowerInvariant())
                    .Select(g => new
                    {
                        Extension = string.IsNullOrEmpty(g.Key) ? "(no ext)" : g.Key,
                        Count = g.Count(),
                        TotalSize = g.Sum(f => new FileInfo(f).Length)
                    })
                    .OrderByDescending(g => g.Count)
                    .ToList();

                sb.AppendLine("| Type | Count | Total Size |");
                sb.AppendLine("|------|-------|------------|");
                foreach (var group in byExtension.Take(15))
                {
                    sb.AppendLine($"| {group.Extension} | {group.Count} | {FormatSize(group.TotalSize)} |");
                }
                if (byExtension.Count > 15)
                    sb.AppendLine($"| *... {byExtension.Count - 15} more types* | | |");

                // Group by top-level directory
                var byDir = allFiles
                    .Select(f =>
                    {
                        var relative = Path.GetRelativePath(basePath, f);
                        var parts = relative.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
                        return parts.Length > 1 ? parts[0] : "(root)";
                    })
                    .GroupBy(d => d)
                    .Select(g => new { Dir = g.Key, Count = g.Count() })
                    .OrderByDescending(g => g.Count)
                    .ToList();

                if (byDir.Count > 1)
                {
                    sb.AppendLine();
                    sb.AppendLine("**By Directory:**");
                    foreach (var dir in byDir.Take(10))
                    {
                        sb.AppendLine($"- `{dir.Dir}/`: {dir.Count} files");
                    }
                }

                // Totals
                var totalSize = allFiles.Sum(f => new FileInfo(f).Length);
                sb.AppendLine();
                sb.AppendLine($"**Total:** {allFiles.Length} files, {FormatSize(totalSize)}");

                return sb.ToString();
            }
            catch (Exception ex)
            {
                return $"Error getting workspace stats: {ex.Message}";
            }
        }

        private string ExecuteRecent(string basePath)
        {
            try
            {
                var allFiles = Directory.GetFiles(basePath, "*", SearchOption.AllDirectories)
                    .Select(f => new FileInfo(f))
                    .OrderByDescending(f => f.LastWriteTimeUtc)
                    .Take(20)
                    .ToList();

                if (allFiles.Count == 0)
                    return "Workspace is empty. No files generated yet.";

                var sb = new StringBuilder();
                sb.AppendLine("## Recently Modified Files\n");
                sb.AppendLine("| Modified | File | Size |");
                sb.AppendLine("|----------|------|------|");

                foreach (var file in allFiles)
                {
                    var relative = Path.GetRelativePath(basePath, file.FullName);
                    var age = DateTime.UtcNow - file.LastWriteTimeUtc;
                    var timeStr = age.TotalMinutes < 60 ? $"{age.TotalMinutes:F0}m ago"
                        : age.TotalHours < 24 ? $"{age.TotalHours:F0}h ago"
                        : $"{age.TotalDays:F0}d ago";
                    sb.AppendLine($"| {timeStr} | `{relative}` | {FormatSize(file.Length)} |");
                }

                return sb.ToString();
            }
            catch (Exception ex)
            {
                return $"Error getting recent files: {ex.Message}";
            }
        }

        private Models.Projects.Project? FindProject(string projectIdOrName)
        {
            var project = _projectService.GetProject(projectIdOrName);
            if (project == null)
            {
                var all = _projectService.GetAllProjects();
                project = all.FirstOrDefault(p => p.Name.Equals(projectIdOrName, StringComparison.OrdinalIgnoreCase));
            }
            return project;
        }

        private static string GetFileIcon(string fileName)
        {
            var ext = Path.GetExtension(fileName).ToLowerInvariant();
            return ext switch
            {
                ".cs" or ".java" or ".py" or ".rb" or ".go" => "📄",
                ".js" or ".ts" or ".jsx" or ".tsx" => "📜",
                ".html" or ".htm" or ".razor" => "🌐",
                ".css" or ".scss" or ".less" => "🎨",
                ".json" or ".xml" or ".yaml" or ".yml" => "📋",
                ".md" or ".txt" or ".rst" => "📝",
                ".png" or ".jpg" or ".svg" or ".gif" => "🖼️",
                ".sql" => "🗄️",
                ".sh" or ".bat" or ".ps1" => "⚙️",
                ".csproj" or ".sln" or ".slnx" => "🔧",
                _ => "📄"
            };
        }

        private static string FormatSize(long bytes)
        {
            if (bytes < 1024) return $"{bytes}B";
            if (bytes < 1024 * 1024) return $"{bytes / 1024.0:F1}KB";
            return $"{bytes / (1024.0 * 1024):F1}MB";
        }
    }
}
